# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='title',
        ),
        migrations.AlterField(
            model_name='photos',
            name='img',
            field=models.TextField(),
        ),
    ]
