# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0002_auto_20191119_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
