# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0010_auto_20191120_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetect',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='name',
        ),
    ]
