# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0011_auto_20191120_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetect',
            name='img',
            field=models.ImageField(upload_to='/ml'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='img',
            field=models.ImageField(upload_to='/media'),
        ),
    ]
